applicationType: desktop
locale: en
vault: ./vault
features:
  favorites: true
  tasks: true
  pinned: true
  nonDistractionMode: true
  noteWebhook: true
notes:
  trashRetentionDays: 30
editor:
  autosaveDelay: 2000
  assetsFolder: assets
layout:
  showInspectorPanel: true
  showSidebarPanel: true
  showNotesListPanel: true
theme:
  accentColor: '#3f57dfff'
