applicationType: desktop
locale: en
vault: ./vault

editor:
  autosaveDelay: 2000

layout:
  showInspectorPanel: true
  showSidebarPanel: true
  showNotesListPanel: true

theme:
  accentColor: '#3f57dfff'
